### PR TITLE
feat: add ens name and avatar support

### PR DESCRIPTION
**Pull request by bigint**
Screenshot 2021-12-24 at 10 08 25 AM

### CODE REVIEW

**Comment by bigint** [comment]
Resolved conflicts 🤗

**Comment by donguks** [comment]
Thanks, @bigint 
For merging, There are things to check.
- [ ] The deployment should not break our new version.
- [ ] @davatar/react should not have security issues.

**Comment by bigint** [comment]
@donguks 

- `@davatar/react` has no security issue I tested with all possible xss images, none of those got resolved, it resolves only the valid address with valid images 🤗 
- Spacing is fixed now
Screenshot 2021-12-27 at 12 07 57 PM
Screenshot 2021-12-27 at 12 11 44 PM

**Comment by bigint** [comment]
@donguks If you want to test make a deploy preview and test in production 🙇🏻

**Comment by donguks** [comment]
@bigint 
Good!
I will merge your PR soon after checking `@davatar/react`

**Comment by bigint** [comment]
Great thanks @donguks looking forward for it, if this got merged the platform will be featured on ens.domains homepage 😄

**Comment by bigint** [comment]
Screenshot 2021-12-27 at 4 12 37 PM

Just a heads up, it works very cool In prod 🎉

**Comment by bigint** [comment]
@donguks Hope it will be merged before 2022 🤞🏻 

ENS have a goal of 420 integrations in 2021

https://twitter.com/BrantlyMillegan/status/1473703222636392451

**Pull request merged**
